/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.Insets;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import laboclinv01.ComboBoxRender;

/**
 *
 * @author Lenovo
 */
public class Empresa800 extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private int selectedRow = 0;
    
    /**
     * Creates new form Empresa
     */
    public Empresa800() {
        initComponents();
        initTable();
        btnAniadir.setMnemonic(KeyEvent.VK_A);
    }
    
    private void initTable(){
        dtm = (DefaultTableModel) patientsTable.getModel();
        
        TableColumn tc;
        DefaultCellEditor dce;
        JTextField jtf = new JTextField();
        jtf.setBorder(null);
        jtf.setMargin(new Insets(0,0,0,0));
        dce = new DefaultCellEditor(jtf);
        tc = patientsTable.getColumnModel().getColumn(1);
        tc.setCellEditor(dce);
        
        JComboBox<String> jcb = new JComboBox(new String[]{"F","M"});
        DefaultCellEditor dcbce = new DefaultCellEditor(jcb);
        tc = patientsTable.getColumnModel().getColumn(6);
        //tc.setCellRenderer(new ComboBoxRender(jcb));
        tc.setCellEditor(dcbce);
        
        dtm.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent tme) {
                if(tme.getType() == TableModelEvent.UPDATE){
                    
                    
                    
                    TableModel tm = (TableModel) tme.getSource();
                    
                    int fila = tme.getFirstRow();
                    int columna = tme.getColumn();
                    
                    if(columna == 4){
                    
                        String fechaNac = dtm.getValueAt(fila, columna).toString();
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                        try {
                            Date date = sdf.parse(fechaNac);

                            LocalDate ldb = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                            LocalDate ldn = LocalDate.now();
                            Period p = Period.between(ldb, ldn);
                            int aux = p.getYears();
                            String val;
                            if(aux < 1){
                                val = "" + p.getMonths() + " meses, " + p.getDays() + " días";
                            }else
                                val = "" + aux + " años";
                            
                            dtm.setValueAt(val, fila, columna+1);
                            
                        } catch (ParseException ex) {
                            JOptionPane.showMessageDialog(null, ex.getMessage());
                        }
                    }
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientsTable = new javax.swing.JTable();
        btnAniadir = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        patientsTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        patientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CI", "Nombres", "Apellido Paterno", "Apellido Materno", "Fecha Nacimiento", "Edad", "Sexo"
            }
        ));
        patientsTable.setAutoscrolls(false);
        patientsTable.setRowHeight(19);
        patientsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(patientsTable);
        if (patientsTable.getColumnModel().getColumnCount() > 0) {
            patientsTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            patientsTable.getColumnModel().getColumn(6).setPreferredWidth(7);
        }

        btnAniadir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAniadir.setText("Añadir");
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });

        btnQuitar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de pacientes para Empresas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAniadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuitar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAniadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void patientsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientsTableMouseClicked
        selectedRow = ((JTable)evt.getSource()).getSelectedRow();
    }//GEN-LAST:event_patientsTableMouseClicked

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
        TableColumn tc;
        JComboBox<String> jcb = new JComboBox(new String[]{"F","M"});
        DefaultCellEditor dcbce = new DefaultCellEditor(jcb);
        tc = patientsTable.getColumnModel().getColumn(6);
        tc.setCellEditor(dcbce);
        
        String[] os = new String[patientsTable.getColumnCount()];
        dtm.addRow(os);
        
        patientsTable.setRowSelectionInterval(dtm.getRowCount()-1, dtm.getRowCount()-1);
        patientsTable.setColumnSelectionInterval(0, 0);
        
        focusCell(dtm.getRowCount()-1,0);
    }//GEN-LAST:event_btnAniadirActionPerformed

    private void focusCell(int row, int column){
        if(patientsTable.editCellAt(row, column)){
            patientsTable.getEditorComponent().requestFocusInWindow();
        }
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
//        String query = "INSERT INTO paciente VALUES (0,?,?,?,?,?,?,?,0)";
//        Connection con = SqlConector.conectar();
//        try {
//            PreparedStatement ps = con.prepareStatement(query);
//            Vector<Vector> vData = dtm.getDataVector();
//            
//            for(Vector<String> row: vData){
//                for(int i=0;i<7;i++)
//                    ps.setString(i+1, row.elementAt(i));
//                ps.executeUpdate();
//                ps.clearParameters();
//            }
//            
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(this, "Error " + ex.getErrorCode() + ":" + ex.getMessage());
//            Logger.getLogger(Empresa800.class.getName()).log(Level.SEVERE, null, ex);
//        }
        if(dtm.getRowCount() > 0){
            Vector<Vector> vData = dtm.getDataVector();
            EmpresaExamenes ventana = new EmpresaExamenes(vData);
            ventana.addWindowListener(new WindowListener() {
                @Override
                public void windowOpened(WindowEvent we) {
                }

                @Override
                public void windowClosing(WindowEvent we) {
                }

                @Override
                public void windowClosed(WindowEvent we) {
                    setVisible(true);
                }

                @Override
                public void windowIconified(WindowEvent we) {
                }

                @Override
                public void windowDeiconified(WindowEvent we) {
                }

                @Override
                public void windowActivated(WindowEvent we) {
                }

                @Override
                public void windowDeactivated(WindowEvent we) {
                }
            });
            this.setVisible(false);
            ventana.setVisible(true);
        }else{
            String message = "La tabla no contiene datos, añada algunos datos";
            JOptionPane.showMessageDialog(this, message);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        dtm.removeRow(selectedRow);
    }//GEN-LAST:event_btnQuitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresa800.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Empresa800().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadir;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientsTable;
    // End of variables declaration//GEN-END:variables
}
